################################
# GENERAL CONFIGURATION
################################
language: python
os: linux
dist: xenial
group: travis_latest

################################
# TEST MATRIX
################################
python:
  - 3.7
  - nightly

################################
# BRANCH FILTER
################################
branches:
  only:
    - staging

################################
# RESULT NOTIFICATIONS
################################
notifications:
  recipients:
    - dante.signal31@gmail.com
  on_success: always
  on_failure: always

################################
# TESTING
################################
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libssl1.0.0
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install codecov pytest-cov
script:
  - pytest -v -n auto --cov-report=xml --cov=test_common_python
after_success:
  - codecov

################################
# DEPLOYMENT
################################
jobs:
  allow_failures:
    # Actually I only build with latest stable python release, but I want
    # to be aware in advance if any dev python version is going to crash
    # my future builds.
    - python: nightly
  include:
    # Update master branch.
    - stage: Branch merge to production branch
      python: 3.7
      env:
        - PYTHONPATH="${PYTHONPATH}:${TRAVIS_BUILD_DIR}"
      if: branch = staging
      script:
        - ci_scripts/merge_with_production
    # Upload packages to Python Package Index.
    - stage: Pypi deployment
      python: 3.7
      script: echo "Deploying to Python Package Index..."
      deploy:
        - provider: pypi
          username: "${PYPI_USER}"
          password: "${PYPI_PASSWORD}"
          distributions: "sdist bdist_wheel"
          on:
            branch: staging